apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: graylog
  name: graylog
  namespace: graylog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graylog
  serviceName: graylog
  template:
    metadata:
      labels:
        app: graylog
    spec:
      containers:
        - env:
            - name: GRAYLOG_PASSWORD_SECRET
              value: somepasswordpepper
            - name: GRAYLOG_ROOT_PASSWORD_SHA2
              value: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
            - name: GRAYLOG_ELASTICSEARCH_HOSTS
              value: http://elasticsearch.graylog.svc.cluster.local:9200
            - name: GRAYLOG_MONGODB_URI
              value: mongodb://mongodb.graylog.svc.cluster.local:27017/graylog
            - name: GRAYLOG_HTTP_EXTERNAL_URI
              value: http://192.168.102.101:31000/
            - name: GRAYLOG_ROOT_TIMEZONE
              value: Asia/Shanghai
          image: graylog/graylog:4.1.3-1
          imagePullPolicy: IfNotPresent
          name: graylog
          ports:
            - containerPort: 9000
              protocol: TCP
            - containerPort: 1514
              protocol: TCP
            - containerPort: 12201
              protocol: TCP
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: "2"
              memory: 2Gi
          volumeMounts:
            - mountPath: /usr/share/graylog/data/journal
              name: graylog-persistent-storage
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: graylog-persistent-storage
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 2Gi
        storageClassName: nfs-storage

---
apiVersion: v1
kind: Service
metadata:
  name: graylog
  namespace: graylog
spec:
  ports:
    - name: "9000"
      nodePort: 31000
      port: 9000
      protocol: TCP
      targetPort: 9000
    - name: 1514-tcp
      nodePort: 31001
      port: 1514
      protocol: TCP
      targetPort: 1514
    - name: 1514-udp
      nodePort: 31002
      port: 1514
      protocol: UDP
      targetPort: 1514
    - name: 12201-tcp
      nodePort: 31003
      port: 12201
      protocol: TCP
      targetPort: 12201
    - name: 12201-udp
      nodePort: 31004
      port: 12201
      protocol: UDP
      targetPort: 12201
  selector:
    app: graylog
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: graylog-svc
  namespace: graylog
spec:
  ports:
    - name: 12201-tcp
      port: 12201
      protocol: TCP
      targetPort: 12201
    - name: 12201-udp
      port: 12201
      protocol: UDP
      targetPort: 12201
  selector:
    app: graylog
  type: ClusterIP
