apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mongodb
  name: mongodb
  namespace: graylog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  serviceName: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - image: bitnami/mongodb:4.4.10-debian-10-r20
          imagePullPolicy: IfNotPresent
          name: mongodb
          ports:
            - containerPort: 27017
              name: mongodb
              protocol: TCP
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: "2"
              memory: 2Gi
          volumeMounts:
            - mountPath: /etc/localtime
              name: localtime
            - mountPath: /bitnami/mongodb
              name: mongodb-persistent-storage
      restartPolicy: Always
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
  volumeClaimTemplates:
    - metadata:
        name: mongodb-persistent-storage
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: 2Gi
        storageClassName: nfs-storage

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: graylog
spec:
  ports:
    - name: mongodb
      port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: mongodb
  type: ClusterIP
