apiVersion: v1
kind: PersistentVolume
metadata:
  name: drone-runner-kube-pv
  namespace: drone-ci
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs-client
  nfs:
    path: /data/drone_runner_kube_nfs_data
    server: 192.168.101.55

