apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drone-runner-kube-pvc
  namespace: drone-ci
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: drone-runner-kube-pv
